version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ugi_rankings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    restart: "no"
    # Override to run specific commands
    # docker-compose run app node dist/index.js rankings

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=ugi_rankings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
